---
title: "QMM-ast 2.3"
author: "SAMIKSHA VENUGOPAL"
date: "10/2/2022"
output: html_document
---
```{r}
library(lpSolveAPI)
weigelt_linear.lp <- make.lp(11,9)
```

```{r}
#obj function-max
set.objfn(weigelt_linear.lp, c(420,360,300,420,360,300,420,360,300))
lp.control(weigelt_linear.lp,sense= 'max')

```

```{r}
#obj function-max
set.objfn(weigelt_linear.lp, c(420,360,300,420,360,300,420,360,300))
lp.control(weigelt_linear.lp,sense= 'max')

#storage

set.row(weigelt_linear.lp, 1, c(20,15,12),indices = c(1,2,3))
set.row(weigelt_linear.lp, 2, c(20,15,12),indices = c(4,5,6))
set.row(weigelt_linear.lp, 3, c(20,15,12),indices = c(7,8,9))

# excess capacity
set.row(weigelt_linear.lp, 4, c(1,1,1),indices = c(1,2,3))
set.row(weigelt_linear.lp, 5, c(1,1,1),indices = c(4,5,6))
set.row(weigelt_linear.lp, 6, c(1,1,1),indices = c(7,8,9))

#sales

set.row(weigelt_linear.lp, 7, c(1,1,1),indices = c(1,4,7))
set.row(weigelt_linear.lp, 8, c(1,1,1),indices = c(2,5,8))
set.row(weigelt_linear.lp, 9, c(1,1,1),indices = c(3,6,9))


#Percent 

set.row(weigelt_linear.lp, 10, c(0.0013,0.0013,0.0013,-0.0011,-0.0011,-0.0011),indices = c(1,2,3,4,5,6))
set.row(weigelt_linear.lp, 11, c(0.0013,0.0013,0.0013,-0.0022,-0.0022,-0.0022),indices = c(1,2,3,7,8,9))


#rhs and sign 

rhs <-c(13000,12000,5000,750,900,450,900,1200,750,0,0)
set.rhs(weigelt_linear.lp,rhs)
set.constr.type(weigelt_linear.lp, c("<=","<=","<=","<=","<=","<=","<=","<=","<=","=","="))

#name
varname <- c("P1L","P1M","P1S","P2L","P2M","P2S","P3L","P3M","P3S")
constrname <-c("Storage1","Storage2","Storage3","ES1","ES2","ES3","Sales1","Sales2","Sales3",
               "Percentage1,Percent2")

weigelt_linear.lp

solve(weigelt_linear.lp)
get.objective(weigelt_linear.lp)
solution <- data.frame(varname, get.variables(weigelt_linear.lp))
colnames(solution) <- c("variables,value")
solution

```

